# Generated by Django 5.0.2 on 2026-02-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de suscripción')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelación')),
            ],
            options={
                'verbose_name': 'suscriptor',
                'verbose_name_plural': 'suscriptores',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('subject', models.CharField(max_length=200, verbose_name='asunto del email')),
                ('content', models.TextField(verbose_name='contenido HTML')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sent', 'Enviado')], default='draft', max_length=20, verbose_name='estado')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='programado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total de destinatarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('devotional', models.ForeignKey(blank=True, help_text='Devocional asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devotionals.devotional', verbose_name='devocional')),
            ],
            options={
                'verbose_name': 'campaña de newsletter',
                'verbose_name_plural': 'campañas de newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
