# Generated by Django 5.0.2 on 2026-02-03 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descripción')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='contenido')),
                ('material_type', models.CharField(choices=[('study', 'Estudio Bíblico'), ('guide', 'Guía de Oración'), ('article', 'Artículo'), ('video', 'Video'), ('audio', 'Audio'), ('ebook', 'E-book')], max_length=20, verbose_name='tipo de material')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='archivo')),
                ('external_url', models.URLField(blank=True, help_text='YouTube, Drive, etc.', verbose_name='URL externa')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='materials/thumbnails/', verbose_name='miniatura')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='etiquetas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='descargas')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['-created_at'],
            },
        ),
    ]
