# Generated by Django 5.0.2 on 2026-02-03 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon', models.CharField(blank=True, help_text='Emoji o clase CSS', max_length=50, verbose_name='icono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenido')),
                ('is_approved', models.BooleanField(default=False, verbose_name='aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('bible_verse', models.CharField(max_length=500, verbose_name='versículo bíblico')),
                ('bible_reference', models.CharField(help_text='Ej: Juan 3:16', max_length=100, verbose_name='referencia bíblica')),
                ('content', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('reflection', ckeditor.fields.RichTextField(blank=True, verbose_name='reflexión')),
                ('prayer', models.TextField(blank=True, verbose_name='oración')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas', max_length=300, verbose_name='etiquetas')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='devotionals/', verbose_name='imagen destacada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('scheduled', 'Programado')], default='draft', max_length=20, verbose_name='estado')),
                ('publish_date', models.DateField(verbose_name='fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vistas')),
            ],
            options={
                'verbose_name': 'devocional',
                'verbose_name_plural': 'devocionales',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ['-created_at'],
            },
        ),
    ]
