# Generated by Django 5.0.2 on 2026-02-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='devotional',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='devotional',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devotionals.category', verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='comment',
            name='devotional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devotionals.devotional', verbose_name='devocional'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='devotional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='devotionals.devotional', verbose_name='devocional'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='devotional',
            index=models.Index(fields=['-publish_date'], name='devotionals_publish_4bc81b_idx'),
        ),
        migrations.AddIndex(
            model_name='devotional',
            index=models.Index(fields=['status'], name='devotionals_status_901558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'devotional')},
        ),
    ]
