# Generated by Django 5.0.1 on 2026-03-24 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Tipo de contenido')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID del contenido')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del autor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Envío de contenido',
                'verbose_name_plural': 'Envíos de contenido',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('content_submitted', 'Contenido enviado a revisión'), ('content_approved', 'Contenido aprobado'), ('content_rejected', 'Contenido rechazado'), ('content_published', 'Contenido publicado'), ('comment_reply', 'Respuesta a comentario'), ('mention', 'Mención'), ('system', 'Sistema')], max_length=30, verbose_name='Tipo de notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Enlace')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='workflow_no_user_id_7a7502_idx'), models.Index(fields=['-created_at'], name='workflow_no_created_d1a9a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Tipo de contenido')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID del contenido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('revision_required', 'Requiere Revisión')], default='pending', max_length=20, verbose_name='Estado de revisión')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Autor del contenido')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='workflow_re_content_58a6e2_idx'), models.Index(fields=['reviewer', 'status'], name='workflow_re_reviewe_3a984d_idx'), models.Index(fields=['author', 'status'], name='workflow_re_author__bcb797_idx')],
            },
        ),
    ]
