# Generated by Django 5.0.1 on 2026-03-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total de visitas')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Visitantes únicos')),
                ('article_views', models.PositiveIntegerField(default=0, verbose_name='Vistas de artículos')),
                ('devotional_views', models.PositiveIntegerField(default=0, verbose_name='Vistas de devocionales')),
                ('study_views', models.PositiveIntegerField(default=0, verbose_name='Vistas de estudios')),
                ('blog_views', models.PositiveIntegerField(default=0, verbose_name='Vistas de blog')),
                ('new_subscribers', models.PositiveIntegerField(default=0, verbose_name='Nuevos suscriptores')),
            ],
            options={
                'verbose_name': 'Estadística diaria',
                'verbose_name_plural': 'Estadísticas diarias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='Tipo de contenido')),
                ('object_id', models.PositiveIntegerField()),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total de vistas')),
                ('unique_views', models.PositiveIntegerField(default=0, verbose_name='Vistas únicas')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Última vista')),
                ('content_type_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Estadística de contenido',
                'verbose_name_plural': 'Estadísticas de contenido',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Artículo'), ('devocional', 'Devocional'), ('estudio', 'Estudio bíblico'), ('blog', 'Entrada de blog')], max_length=20, verbose_name='Tipo de contenido')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referente')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de visita')),
                ('content_type_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vista de página',
                'verbose_name_plural': 'Vistas de páginas',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-viewed_at'], name='analytics_p_content_1af0e8_idx'), models.Index(fields=['-viewed_at'], name='analytics_p_viewed__863699_idx')],
            },
        ),
    ]
