# Generated by Django 5.0.1 on 2026-03-24 03:49

import apps.media_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_manager.mediafolder', verbose_name='Carpeta padre')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.media_manager.models.get_file_upload_path, verbose_name='Archivo')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de archivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('alt_text', models.CharField(blank=True, help_text='Para accesibilidad', max_length=200, verbose_name='Texto alternativo')),
                ('tags', models.CharField(blank=True, help_text='Separadas por coma', max_length=500, verbose_name='Etiquetas')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', verbose_name='Miniatura')),
                ('folder', models.CharField(blank=True, max_length=200, verbose_name='Carpeta')),
                ('used_in', models.TextField(blank=True, editable=False, help_text='IDs de contenido donde se usa este archivo', verbose_name='Usado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_type'], name='media_manag_file_ty_522fe8_idx'), models.Index(fields=['uploader', 'file_type'], name='media_manag_uploade_1cfec4_idx'), models.Index(fields=['-created_at'], name='media_manag_created_4461be_idx')],
            },
        ),
    ]
