# Generated by Django 5.0.1 on 2026-03-24 03:22

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/%Y/%m/', verbose_name='Imagen destacada')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Extracto')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijo en inicio')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Permitir comentarios')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to='content.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/%Y/%m/', verbose_name='Imagen destacada')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Articulo destacado')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Tiempo de lectura (minutos)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to='content.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/%Y/%m/', verbose_name='Imagen destacada')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('verse_reference', models.CharField(max_length=200, verbose_name='Referencia bíblica')),
                ('verse_text', models.TextField(blank=True, verbose_name='Texto del versículo')),
                ('is_daily', models.BooleanField(default=True, verbose_name='Devocional del día')),
                ('date', models.DateField(blank=True, null=True, unique=True, verbose_name='Fecha del devocional')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to='content.category', verbose_name='Categoría')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionales',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudioBiblico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/%Y/%m/', verbose_name='Imagen destacada')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('bible_book', models.CharField(max_length=100, verbose_name='Libro bíblico')),
                ('bible_chapter', models.PositiveIntegerField(verbose_name='Capítulo')),
                ('bible_verse_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versículo inicial')),
                ('bible_verse_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versículo final')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Dificultad')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to='content.category', verbose_name='Categoría')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Estudio Bíblico',
                'verbose_name_plural': 'Estudios Bíblicos',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='content_cat_slug_d6cc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='content_cat_is_acti_04babc_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='content_blo_slug_441465_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='content_blo_status_e22d68_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='content_blo_publish_96cb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-views'], name='content_blo_views_76b7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='content_art_slug_d82f31_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='content_art_status_e667c8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='content_art_publish_be1b80_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views'], name='content_art_views_8c60ba_idx'),
        ),
        migrations.AddIndex(
            model_name='devocional',
            index=models.Index(fields=['slug'], name='content_dev_slug_7616fb_idx'),
        ),
        migrations.AddIndex(
            model_name='devocional',
            index=models.Index(fields=['status'], name='content_dev_status_6ce06b_idx'),
        ),
        migrations.AddIndex(
            model_name='devocional',
            index=models.Index(fields=['-published_at'], name='content_dev_publish_c63bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='devocional',
            index=models.Index(fields=['-views'], name='content_dev_views_2235ae_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiobiblico',
            index=models.Index(fields=['slug'], name='content_est_slug_ddfd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiobiblico',
            index=models.Index(fields=['status'], name='content_est_status_1b15de_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiobiblico',
            index=models.Index(fields=['-published_at'], name='content_est_publish_1d4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiobiblico',
            index=models.Index(fields=['-views'], name='content_est_views_f9ddd2_idx'),
        ),
    ]
