# Generated by Django 5.0.1 on 2026-03-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('content_html', models.TextField(verbose_name='Contenido HTML')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='Destinatarios')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Aperturas')),
            ],
            options={
                'verbose_name': 'Archivo de boletín',
                'verbose_name_plural': 'Archivos de boletines',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el suscriptor recibe los boletines', verbose_name='Activo')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el email ha sido verificado', verbose_name='Verificado')),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('unsubscribed_reason', models.TextField(blank=True, verbose_name='Razón de cancelación')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('content_html', models.TextField(blank=True, verbose_name='Contenido HTML')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sent', 'Enviado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Fecha y hora programada para el envío', null=True, verbose_name='Programado para')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='Destinatarios')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Aperturas')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Boletín',
                'verbose_name_plural': 'Boletines',
                'ordering': ['-created_at'],
            },
        ),
    ]
